### ISSUE TITLE
[Feature Request] Add SimultaneousKeyPresses::Option::FILTERTHROUGH

### ISSUE THREAD

**Issue by nkgm** [tekezo/Karabiner#382]
Quick example:

Let's map `D` to `SHIFT`, `F` to `OPTION`, and use `J K I L` keys for arrows. Instead of using `SPACE` as the activator key, I want these keys to become active when pressed together in certain combinations with each other, and then remain active until I hit `ESCAPE` (a more difficult scenario would be until both `D` and `F` are released). Currently, if I use `__SimultaneousKeyPresses__ KeyCode::D, KeyCode::F`, I can't treat those keys as individual modifiers. In other words, I will get `OPTION+SHIFT` even when `D` has been released. With the requested `FILTERTHROUGH` option I could:
```xml
<autogen>
    __SimultaneousKeyPresses__ KeyCode::D, KeyCode::F, 
    KeyCode::VK_LOCK_EXTRA1_FORCE_ON, 
    SimultaneousKeyPresses::Option:FILTERTHROUGH
</autogen>

<block>
    <modifier_only>ModifierFlag::EXTRA1</modifier_only>
    <autogen>__KeyToKey__ KeyCode::F, KeyCode::OPTION_L</autogen>
    <autogen>__KeyToKey__ KeyCode::D, KeyCode::SHIFT_L</autogen>
</block
```
So essentially `FILTERTHROUGH` would allow the key events to be processed by the next handler.

Does this make sense? Is there some other way to achieve the same outcome?

**Comment by tekezo** [comment]
You can use `Option::SIMULTANEOUSKEYPRESSES_RAW` to apply `__KeyToKey__` after `__SimultaneousKeyPresses__`.

But this autogen is more simple:

```
    <autogen>
      __SimultaneousKeyPresses__ KeyCode::D, KeyCode::F,
      KeyCode::VK_LOCK_EXTRA1_FORCE_ON,
      KeyCode::OPTION_L | ModifierFlag::SHIFT_L,
    </autogen>
```

**Comment by nkgm** [comment]
The problem there would be that if I release one of the keys while the other one is still down, I'll still get `OPTION + SHIFT`. I would expect it to work as such:

Press D+F = OPTION + SHIFT
Release D while F is still down = OPTION

As far as I'm aware `SimultaneousKeyPresses` will treat `D+F` as one big key.

**Comment by tekezo** [comment]
I see.
I've added `Option::SIMULTANEOUSKEYPRESSES_RAW_WITH_ORIGINAL_EVENTS` has been added at the latest beta version (v10.6.40).
That acts as your SimultaneousKeyPresses::Option:FILTERTHROUGH.

https://github.com/tekezo/Karabiner/blob/master/src/core/server/Resources/include/checkbox/samples.xml#L1936-L1961


How to upgrade to the latest beta version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates

**Comment by nkgm** [comment]
This is simply beautiful. Thank you so much!

**Comment by nkgm** [comment]
It works for my original case:
```xml
<modifierdef>NKGM</modifierdef>

<block>
	<modifier_only>ModifierFlag::NKGM</modifier_only>
	<autogen>
		__KeyToKey__ KeyCode::J, KeyCode::CURSOR_LEFT
	</autogen>
	<autogen>
		__KeyToKey__ KeyCode::L, KeyCode::CURSOR_RIGHT
	</autogen>
	<autogen>
		__KeyToKey__ KeyCode::K, KeyCode::CURSOR_DOWN
	</autogen>
	<autogen>
		__KeyToKey__ KeyCode::I, KeyCode::CURSOR_UP
	</autogen>

	<autogen>
		__KeyToKey__ KeyCode::F, KeyCode::OPTION_L
	</autogen>
	<autogen>
		__KeyToKey__ KeyCode::D, KeyCode::SHIFT_L
	</autogen>
</block>

<autogen>
	__SimultaneousKeyPresses__ 
	__{ KeyCode::D, KeyCode::F, }__
	KeyCode::VK_LOCK_NKGM_FORCE_ON,
	Option::SIMULTANEOUSKEYPRESSES_RAW_WITH_ORIGINAL_EVENTS
</autogen>
```
Now let's assume I want the lock off when both `D` and `F` have been released:
```xml
<autogen>
	__SimultaneousKeyPresses__ 
	__{ KeyCode::D, KeyCode::F, }__
	KeyCode::VK_MODIFIER_NKGM,
	Option::SIMULTANEOUSKEYPRESSES_RAW_WITH_ORIGINAL_EVENTS
</autogen>
```
The above won't work. It appears that `NKGM` is not visible to the `<block>` above, and I will still get `D` and `F`.

If however I try this:
```xml
<autogen>
	__SimultaneousKeyPresses__ 
	__{ KeyCode::D, KeyCode::F, }__
	KeyCode::VK_MODIFIER_EXTRA1,
	Option::SIMULTANEOUSKEYPRESSES_RAW,
	Option::SIMULTANEOUSKEYPRESSES_RAW_WITH_ORIGINAL_EVENTS
</autogen>

<autogen>
	__KeyToKey__ KeyCode::VK_MODIFIER_EXTRA1, KeyCode::VK_MODIFIER_NKGM,
</autogen>
```
it will work as intended: `D` and `F` will work as expected, and when each key has been released once, `NKGM` is released as well. 

**NOTE**: If I was to `D_down + F_down`->`D_up`->`D_down`->`F_up`, now effectively I've lost `NKGM` even though both keys were never up at the same time and `D`(=`SHIFT`) is still down. To work with cases like this, it would really help to have `VK_LOCK_NKGM_INCREMENT` and `VK_LOCK_NKGM_DECREMENT`.

About the extra `KeyToKey` step, I don't mind adding it each time (I'll probably need it most of the time anyway), just bringing it to your attention.

**Comment by tekezo** [comment]
Thank you for feedback.
I've fixed this issue at v10.6.41.

And you should put `ModifierFlag::NKGM` in __KeyToKey__ as follows.

```xml
<block>
    <modifier_only>ModifierFlag::NKGM</modifier_only>
    <autogen>
        __KeyToKey__ KeyCode::F, KeyCode::OPTION_L, ModifierFlag::NKGM,
    </autogen>
    <autogen>
        __KeyToKey__ KeyCode::D, KeyCode::SHIFT_L, ModifierFlag::NKGM,
    </autogen>
</block>

<autogen>
    __SimultaneousKeyPresses__ 
    __{ KeyCode::D, KeyCode::F, }__
    KeyCode::VK_MODIFIER_NKGM,
    Option::SIMULTANEOUSKEYPRESSES_RAW_WITH_ORIGINAL_EVENTS
</autogen>
```

**Comment by nkgm** [comment]
Ok so with your help it's coming together quite awesome. Still have a timing related glitch. Here is my config:
```xml
<block>
	<modifier_only>ModifierFlag::NKGM</modifier_only>
	<autogen>
		__KeyToKey__ KeyCode::G, KeyCode::VK_NONE, ModifierFlag::NKGM,
	</autogen>
	<autogen>
		__KeyToKey__ KeyCode::F, KeyCode::OPTION_L, ModifierFlag::NKGM, 
	</autogen>
	<autogen>
		__KeyToKey__ KeyCode::D, KeyCode::SHIFT_L, ModifierFlag::NKGM, 
	</autogen>
	<autogen>
		__KeyToKey__ KeyCode::S, KeyCode::COMMAND_L, ModifierFlag::NKGM, 
	</autogen>
	<autogen>
		__KeyToKey__ KeyCode::A, KeyCode::FN, ModifierFlag::NKGM, 
	</autogen>
	
	<autogen>
		__KeyToKey__ KeyCode::H, KeyCode::CURSOR_LEFT, 
	</autogen>
	<autogen>
		__KeyToKey__ KeyCode::J, KeyCode::CURSOR_DOWN, 
	</autogen>
	<autogen>
		__KeyToKey__ KeyCode::K, KeyCode::CURSOR_UP, 
	</autogen>
	<autogen>
		__KeyToKey__ KeyCode::L, KeyCode::CURSOR_RIGHT, 
	</autogen>
</block>

<!-- D is SHIFT -->
<autogen>
	__SimultaneousKeyPresses__ 
	__{ KeyCode::D, KeyCode::H, }__
	KeyCode::VK_MODIFIER_NKGM,
	Option::SIMULTANEOUSKEYPRESSES_RAW_WITH_ORIGINAL_EVENTS
</autogen>

<autogen>
	__SimultaneousKeyPresses__ 
	__{ KeyCode::D, KeyCode::J, }__
	KeyCode::VK_MODIFIER_NKGM,
	Option::SIMULTANEOUSKEYPRESSES_RAW_WITH_ORIGINAL_EVENTS
</autogen>

<autogen>
	__SimultaneousKeyPresses__ 
	__{ KeyCode::D, KeyCode::K, }__
	KeyCode::VK_MODIFIER_NKGM,
	Option::SIMULTANEOUSKEYPRESSES_RAW_WITH_ORIGINAL_EVENTS
</autogen>

<autogen>
	__SimultaneousKeyPresses__ 
	__{ KeyCode::D, KeyCode::L, }__
	KeyCode::VK_MODIFIER_NKGM,
	Option::SIMULTANEOUSKEYPRESSES_RAW_WITH_ORIGINAL_EVENTS
</autogen>
```
Problem: pressing `D+H` should give me `SHIFT+LEFT` regardless of which key was pressed first. Yet, if `H` is pressed marginally before `D`, the first `LEFT` will be without a `SHIFT`.

**Comment by tekezo** [comment]
I see.
I've changed the behavior at v10.6.43.
And change option name. Please replace it.

```diff
- Option::SIMULTANEOUSKEYPRESSES_RAW_WITH_ORIGINAL_EVENTS
+ Option::SIMULTANEOUSKEYPRESSES_POST_FROM_EVENTS_AS_RAW
```

**Comment by nkgm** [comment]
It works great so far. Every time you fix something, I stride along, and then I uncover something else, so I apologize if this is becoming cumbersome. This one, I'm not even sure whether it's a bug or not. Quoting updated configuration:
```xml
<block>
    <modifier_only>ModifierFlag::NKGM</modifier_only>
    <autogen>
        __KeyToKey__ KeyCode::G, KeyCode::VK_MODIFIER_NKGM, 
    </autogen>
    <autogen>
        __KeyToKey__ KeyCode::F, KeyCode::OPTION_L, ModifierFlag::NKGM, 
    </autogen>
    <autogen>
        __KeyToKey__ KeyCode::D, KeyCode::SHIFT_L, ModifierFlag::NKGM, 
    </autogen>
    <autogen>
        __KeyToKey__ KeyCode::S, KeyCode::COMMAND_L, ModifierFlag::NKGM, 
    </autogen>
    <autogen>
        __KeyToKey__ KeyCode::A, KeyCode::FN, ModifierFlag::NKGM, 
    </autogen>

    <autogen>
        __KeyToKey__ KeyCode::H, KeyCode::CURSOR_LEFT, ModifierFlag::NKGM, 
    </autogen>
    <autogen>
        __KeyToKey__ KeyCode::J, KeyCode::CURSOR_DOWN, ModifierFlag::NKGM, 
    </autogen>
    <autogen>
        __KeyToKey__ KeyCode::K, KeyCode::CURSOR_UP, ModifierFlag::NKGM, 
    </autogen>
    <autogen>
        __KeyToKey__ KeyCode::L, KeyCode::CURSOR_RIGHT, ModifierFlag::NKGM, 
    </autogen>
</block>

<!-- D is SHIFT -->
<autogen>
    __SimultaneousKeyPresses__ 
    __{ KeyCode::D, KeyCode::H, }__
    KeyCode::VK_MODIFIER_NKGM,
    Option::SIMULTANEOUSKEYPRESSES_POST_FROM_EVENTS_AS_RAW
</autogen>

<autogen>
    __SimultaneousKeyPresses__ 
    __{ KeyCode::D, KeyCode::J, }__
    KeyCode::VK_MODIFIER_NKGM,
    Option::SIMULTANEOUSKEYPRESSES_POST_FROM_EVENTS_AS_RAW
</autogen>

<autogen>
    __SimultaneousKeyPresses__ 
    __{ KeyCode::D, KeyCode::K, }__
    KeyCode::VK_MODIFIER_NKGM,
    Option::SIMULTANEOUSKEYPRESSES_POST_FROM_EVENTS_AS_RAW
</autogen>

<autogen>
    __SimultaneousKeyPresses__ 
    __{ KeyCode::D, KeyCode::L, }__
    KeyCode::VK_MODIFIER_NKGM,
    Option::SIMULTANEOUSKEYPRESSES_POST_FROM_EVENTS_AS_RAW
</autogen>
```
What I'm not clear about: in this event sequence [`D_down+H_down`->`D_up`->`J_down`->`H_up`->`K_down`], I'll get 'k' even though `J` is still down and already mapped successfully to `DOWN`.

**Comment by tekezo** [comment]
Thank you for feedback! I confirmed.
We need a new option to do it. Please wait for a while.

Note:
If TO_KEY is not modifier, KeyToKey increases TO_MODIFIER temporary.
So, `__KeyToKey__ KeyCode::L, KeyCode::CURSOR_RIGHT, ModifierFlag::NKGM` does not keep ModifierFlag::NKGM for other keys.

**Comment by nkgm** [comment]
This could be another one of these cases where #386 might come in handy (as a workaround perhaps) in `KEYTOKEY_BEFORE_KEYDOWN` and `KEYTOKEY_AFTER_KEYUP`.

It's not crucial for me as I'm now able to move ahead with all these great improvements you've implemented over this last couple of weeks, so thank you for all your hard work. Still looking forward to this new option though!

**Comment by tekezo** [comment]
I've added `Option::KEYTOKEY_INCREASE_MODIFIER_FLAGS` at the latest beta version.
This option allows you to increase flags while pressing key.
Please use it like this:

```xml
      <autogen>
        __KeyToKey__ KeyCode::H, KeyCode::CURSOR_LEFT,

        Option::KEYTOKEY_INCREASE_MODIFIER_FLAGS,
        ModifierFlag::NKGM,
      </autogen>
```

**Comment by nkgm** [comment]
Looking good so far. Don't you think this should be the default behavior?

**Comment by tekezo** [comment]
I'm afraid "Change control-V to command-V" sends unintended command by "control down, V down, control up, space down".
(We should send the normal space key event, but command-space.)

**Comment by nkgm** [comment]
Misplaced?

**Comment by tekezo** [comment]
Excuse me for short description.

You meant that this autogen increases ModifierFlag::NKGM while we are pressing H key as default.
Is it right?

```xml
    <autogen>
        __KeyToKey__ KeyCode::H, KeyCode::CURSOR_LEFT, ModifierFlag::NKGM, 
    </autogen>
```

**Comment by nkgm** [comment]
Yes I meant that it should work like that by default, without having to use `Option::KEYTOKEY_INCREASE_MODIFIER_FLAGS`. What do you think?

About your previous post:

>I'm afraid "Change control-V to command-V" sends unintended command by "control down, V down, control up, space down"

Don't understand where "space down" comes from.

**Comment by tekezo** [comment]
OK.

For example, this autogen will increase command modifier while you press the V key.

```xml
    <autogen>
      __KeyToKey__
      KeyCode::V, MODIFIERFLAG_EITHER_LEFT_OR_RIGHT_CONTROL,
      KeyCode::V, MODIFIERFLAG_EITHER_LEFT_OR_RIGHT_COMMAND,
    </autogen>
```

When we want to paste text and enter a space, we type control-V,space.
If the input key sequence is "control down, V down, control up, space down",
Karabiner changes the key sequence to "command-V, command-space" with that behavior.

I did not change the default behavior and append `Option::KEYTOKEY_INCREASE_MODIFIER_FLAGS` by this reason.

**Comment by nkgm** [comment]
I see now and I agree. I guess this can happen when you're typing really fast, or sometimes lazy. For example, I still get "vues" instead of "values" sometimes because of my homerow config, and it does take some getting used to, but overall it has helped me improve my keystrokes.
